# Generated by Django 4.2.4 on 2023-09-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_version_options_alter_version_version_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'версию', 'verbose_name_plural': 'версии'},
        ),
    ]
